name: Love in focus
favicon: null
layout_spectrum: 0.7281673431862146
typography_spectrum: 0.9590607567224652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.11863350286148489
  lightness: 0.8440443619620055
  saturation: 0.17447977070696652
  rhythmicContrast: 0.30727590015158057
purpose: []
