name: Love in focus
favicon: null
layout_spectrum: 0.76204
typography_spectrum: 0.24759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#063346'
    - '#2d5a81'
    - '#5d82ae'
    - '#8597c2'
    - '#b6bbe0'
  brandStrength: 0.11863350286148489
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.30727590015158057
purpose: []
